title: Gabriel Barbir
description: Cybersecurity writeups focused on detection engineering, threat hunting, and offensive security.
url: https://zero-for683.github.io

minimal_mistakes_skin: dark
remote_theme: "mmistakes/minimal-mistakes@4.26.2"


masthead_title: "Gabriel Barbir"

defaults:
  - scope:
    path: ""
  values:
      masthead: true

author:
  name: "Gabriel Barbir"
  bio: "Cybersecurity Analyst | OSCP | Threat Hunting & Detection"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/gabriel-barbir/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ZeroFor-683"


plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


masthead_title: "Gabriel Barbir"
breadcrumbs: true

header:
  nav: main

main:
  - title: "Writeups"
    url: /categories/
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/



